### ISSUE TITLE
Support for Windows system

### ISSUE THREAD

**Issue by qingbo11** [jodyphelan/tbdb#38]
**Is your feature request related to a problem? Please describe.**
Hello, I am trying to use TB profiler for predicting the drug resistance of a batch of 65 Mtb genomes. Unfortunately we only have windows system available in our workstation. I tried to use the webserver first, but the limitation of 1 GB data was soon reached and cannot accept new submission. Could you please guide me on how to use the webserver basedon windows system in details?

**Describe the solution you'd like**
It could be useful if the installation of TB profiler can be easily conducted on windows system.
The current instruction for how to install it on windows system is difficult to me and I am unable to succeed in it.

Thanks,

**Additional context**

**Comment by jodyphelan** [comment]
Dear @qingbo11 

Please find instructions for Windows systems here: https://jodyphelan.gitbook.io/tb-profiler/quickstart/windows
Let me know if it works ok for you.

**Comment by qingbo11** [comment]
Dear Dr. Jody Phelan,

Thank you for your email. I will try it and let you know.

Best,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by qingbo11** [comment]
Shu, Qingbo has shared OneDrive for Business files with you. To view them, click the links below.
<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_1.fastq.gz>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_1.fastq.gz>
HN1104_SRR067516_1.fastq.gz<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_1.fastq.gz>

<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_2.fastq.gz>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_2.fastq.gz>
HN1104_SRR067516_2.fastq.gz<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/Documents/Attachments/HN1104_SRR067516_2.fastq.gz>

Dear Dr. Jody Phelan,

Thank you. I installed the docker on my computer and added TBProfiler image into it. I still have problem in how to use the command as "/path/to/reads_1.fastq.gz", I uploaded two files for this analysis. Please test them and see if they work. please share with me your command so that I can modify it on my computer to get the same result as yours.

Best regards,


Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by qingbo11** [comment]
To view HN1104_SRR067516_1.fastq.gz, sign in<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/_layouts/15/acceptinvite.aspx?invitation=%7B09DE8561%2D8F67%2D4479%2DB611%2D25A066676EE9%7D&listId=91a359c3%2Df349%2D41a4%2Da2be%2Dd13b81182b53&itemId=9324e263%2D779c%2D418c%2D867a%2D635ae633b6f2> or create an account.

**Comment by qingbo11** [comment]
To view HN1104_SRR067516_2.fastq.gz, sign in<https://wavetulane-my.sharepoint.com/personal/qshu_tulane_edu/_layouts/15/acceptinvite.aspx?invitation=%7BEFEE81B7%2D692D%2D43C4%2D8A96%2D579CB0454FBF%7D&listId=91a359c3%2Df349%2D41a4%2Da2be%2Dd13b81182b53&itemId=83065ee9%2D4819%2D4a61%2D88e9%2D4881a541b7de> or create an account.

**Comment by jodyphelan** [comment]
Hi @qingbo11 

This command worked for me:
```
tb-profiler profile -1 HN1104_SRR067516_1.fastq.gz -2 HN1104_SRR067516_2.fastq.gz  -p HN1104
```

**Comment by qingbo11** [comment]
Dear Dr. Jody Phelan,

Thank you so much. I tried the same code, but the fastq files cannot be found as shown below.
sh-5.0# tb-profiler profile -1 HN1104_SRR067516_1.fastq.gz -2 HN1104_SRR067516_2.fastq.gz  -p HN1104
Using gff file: /usr/local/share/tbprofiler/tbdb.gff
Using ref file: /usr/local/share/tbprofiler/tbdb.fasta
Using barcode file: /usr/local/share/tbprofiler/tbdb.barcode.bed
Using bed file: /usr/local/share/tbprofiler/tbdb.bed
Using json_db file: /usr/local/share/tbprofiler/tbdb.dr.json
Using version file: /usr/local/share/tbprofiler/tbdb.version.json
Using variables file: /usr/local/share/tbprofiler/tbdb.variables.json
Can't find HN1104_SRR067516_1.fastq.gz

I also modified the command and tried again. This time I added the path of the two files as a c drive folder C:\TB Profiler, and it showed an error as below

sh-5.0# tb-profiler profile -1 /c:/TB Profiler/HN1104_SRR067516_1.fastq.gz -2 /c:/TB Profiler/HN1104_SRR067516_2.fastq.gz -p HN1104
usage: tb-profiler [-h] [--version]
                   {profile,vcf_profile,fasta_profile,lineage,collate,reprofile,reformat,create_db,load_library,update_tbdb,version}
                   ...
tb-profiler: error: unrecognized arguments: Profiler/HN1104_SRR067516_1.fastq.gz Profiler/HN1104_SRR067516_2.fastq.gz
sh-5.0# tb-profiler profile -1 /c:/fastq/HN1104_SRR067516_1.fastq.gz -2 /c:/fastq/HN1104_SRR067516_2.fastq.gz -p HN1104
Using gff file: /usr/local/share/tbprofiler/tbdb.gff
Using ref file: /usr/local/share/tbprofiler/tbdb.fasta
Using barcode file: /usr/local/share/tbprofiler/tbdb.barcode.bed
Using bed file: /usr/local/share/tbprofiler/tbdb.bed
Using json_db file: /usr/local/share/tbprofiler/tbdb.dr.json
Using version file: /usr/local/share/tbprofiler/tbdb.version.json
Using variables file: /usr/local/share/tbprofiler/tbdb.variables.json
Can't find /c:/fastq/HN1104_SRR067516_1.fastq.gz

Please teach me how to prepare the file path so that they can be accessed by TB Profiler.

Best regards,


Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by jodyphelan** [comment]
By mounting the windorws folder to `/mnt` in the docker container you shouldn't have to refer to the windows style path. All you should do is first change directory to the /mnt folder by typing:
```
cd /mnt
```

Then you can verify that your fastq files are present by typing `ls`. You should see a list of the files printed to the terminal window.

**Comment by qingbo11** [comment]
Hi Dr. Jody Phelan,

Thank you so much for your help. Now I got the result file from 65 strains as attached. I tried to generate a tree map as you showed in your webpage, and I used the tb-profiler collate code to run the next step. However, it showed an error as below.
My expected output file is the tbprofiler.tree file.

[cid:2ca714bf-2ce7-4fee-90ba-0e1e61898209]

Error message:

sh-5.0# tb-profiler collate
Using gff file: /usr/local/share/tbprofiler/tbdb.gff
Using ref file: /usr/local/share/tbprofiler/tbdb.fasta
Using barcode file: /usr/local/share/tbprofiler/tbdb.barcode.bed
Using bed file: /usr/local/share/tbprofiler/tbdb.bed
Using json_db file: /usr/local/share/tbprofiler/tbdb.dr.json
Using version file: /usr/local/share/tbprofiler/tbdb.version.json
Using variables file: /usr/local/share/tbprofiler/tbdb.variables.json
  0%|                                                                                            | 0/65 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/usr/local/bin/tb-profiler", line 285, in main_collate
    tbp.collate_results(args.prefix,conf,sample_file=args.samples,result_dir=args.dir,reporting_af=args.reporting_af,mark_missing=args.mark_missing)
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in collate_results
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in <listcomp>
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
KeyError: 'drug_resistance_position'

Please see if you can address this error. I have 6 hours behind yours. Please let me know if you need to access this computer.

Best regards,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________

**Comment by qingbo11** [comment]
# tb-profiler error report

* OS: linux
* Program version: 4.0.1
* Program call:
```
{'prefix': 'tbprofiler', 'samples': None, 'dir': 'results', 'full': False, 'all_variants': False, 'mark_missing': False, 'reporting_af': 0.1, 'db': 'tbdb', 'external_db': None, 'func': <function main_collate at 0x7f019096c040>}
```
## Traceback:
```
  File "/usr/local/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/usr/local/bin/tb-profiler", line 285, in main_collate
    tbp.collate_results(args.prefix,conf,sample_file=args.samples,result_dir=args.dir,reporting_af=args.reporting_af,mark_missing=args.mark_missing)
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in collate_results
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in <listcomp>
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
```
## Value:
```
'drug_resistance_position'```


Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________
From: Shu, Qingbo ***@***.***>
Sent: Thursday, November 18, 2021 4:12 PM
To: jodyphelan/tbdb ***@***.***>; jodyphelan/tbdb ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [jodyphelan/tbdb] Support for Windows system (Issue #38)

Hi Dr. Jody Phelan,

Thank you so much for your help. Now I got the result file from 65 strains as attached. I tried to generate a tree map as you showed in your webpage, and I used the tb-profiler collate code to run the next step. However, it showed an error as below.
My expected output file is the tbprofiler.tree file.

[cid:2ca714bf-2ce7-4fee-90ba-0e1e61898209]

Error message:

sh-5.0# tb-profiler collate
Using gff file: /usr/local/share/tbprofiler/tbdb.gff
Using ref file: /usr/local/share/tbprofiler/tbdb.fasta
Using barcode file: /usr/local/share/tbprofiler/tbdb.barcode.bed
Using bed file: /usr/local/share/tbprofiler/tbdb.bed
Using json_db file: /usr/local/share/tbprofiler/tbdb.dr.json
Using version file: /usr/local/share/tbprofiler/tbdb.version.json
Using variables file: /usr/local/share/tbprofiler/tbdb.variables.json
  0%|                                                                                            | 0/65 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/tb-profiler", line 594, in <module>
    args.func(args)
  File "/usr/local/bin/tb-profiler", line 285, in main_collate
    tbp.collate_results(args.prefix,conf,sample_file=args.samples,result_dir=args.dir,reporting_af=args.reporting_af,mark_missing=args.mark_missing)
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in collate_results
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
  File "/usr/local/lib/python3.9/site-packages/tbprofiler/collate.py", line 48, in <listcomp>
    missing_genes = [x["locus_tag"] for x in temp["qc"]["missing_positions"] if x["drug_resistance_position"]=="DR"]
KeyError: 'drug_resistance_position'

Please see if you can address this error. I have 6 hours behind yours. Please let me know if you need to access this computer.

Best regards,

Qingbo Shu
Post-doctoral Fellow
Department of Biochemistry and Molecular Biology
Tulane University School of Medicine
Phone: 346-754-4664
Email: ***@***.***
________________________________
From: Jody Phelan ***@***.***>
Sent: Thursday, November 18, 2021 2:35 AM
To: jodyphelan/tbdb ***@***.***>
Cc: Shu, Qingbo ***@***.***>; Mention ***@***.***>
Subject: Re: [jodyphelan/tbdb] Support for Windows system (Issue #38)


External Sender. Be aware of links, attachments and requests.

By mounting the windorws folder to /mnt in the docker container you shouldn't have to refer to the windows style path. All you should do is first change directory to the /mnt folder by typing:

cd /mnt


Then you can verify that your fastq files are present by typing ls. You should see a list of the files printed to the terminal window.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjodyphelan%2Ftbdb%2Fissues%2F38%23issuecomment-972646041&data=04%7C01%7Cqshu%40tulane.edu%7C11bfdfa70ecb494c015b08d9aa6e6489%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637728213382041904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ygirF6N%2BYPq3WgNh5hvLz5jc4QDKtkBLu3YyU5TFMyo%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATKXG7SRHR7IZJVB6ZP3YG3UMS3FNANCNFSM5HV6GFFQ&data=04%7C01%7Cqshu%40tulane.edu%7C11bfdfa70ecb494c015b08d9aa6e6489%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637728213382051868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5RVxc79kZCwzi3FXR5yRZkoNxuiSD5OvQA5SW%2Fxr7CM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cqshu%40tulane.edu%7C11bfdfa70ecb494c015b08d9aa6e6489%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637728213382051868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I3wAmD6aHPfdw5iHQ5ivEZIbCRYX6qq9CEVchmkZXz4%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cqshu%40tulane.edu%7C11bfdfa70ecb494c015b08d9aa6e6489%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637728213382061818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xv7unmJgMFVNETy43fcvhV%2FQpVppfAOEN6pT0VAAvJY%3D&reserved=0>.
