### ISSUE TITLE
[Errno 2] No such file or directory: 'genes.txt'

### ISSUE THREAD

**Issue by ryobon-dev** [jodyphelan/tbdb#46]
I downloaded tbdb-master and run python parse_db.py.

However, the following error messages appeared. Could you please let me know how I can fix the issue ?

(base) kansensho@DESKTOP-QBEDU0F:/mnt/e/Desktop/tool/tbdb-master$ ls
LICENCE      genome.fasta  scripts                  tbdb.csv                    variables.json
README.md    genome.gff    spoligotype_list.csv     tbdb.other_annotations.csv
barcode.bed  parse_db.py   spoligotype_spacers.txt  tbdb.watchlist.csv
(base) kansensho@DESKTOP-QBEDU0F:/mnt/e/Desktop/tool/tbdb-master$ python parse_db.py
Traceback (most recent call last):
  File "/mnt/e/Desktop/tool/tbdb-master/parse_db.py", line 281, in <module>
    args.func(args)
  File "/mnt/e/Desktop/tool/tbdb-master/parse_db.py", line 202, in main
    gene_info = load_gene_info("genes.txt")
  File "/mnt/e/Desktop/tool/tbdb-master/parse_db.py", line 187, in load_gene_info
    for l in open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'genes.txt'

**Comment by mbhall88** [comment]
I also raised this in #45

**Comment by jodyphelan** [comment]
Thanks @mbhall88, I've now updated the documentation to remove references the parse_db.py script. @ryobon-dev Please refer to https://github.com/jodyphelan/TBProfiler for instructions on how to create the database files for `tb-profiler`
