### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by arnoldbain** [jodyphelan/tbdb#52]
**Describe the bug**
Am using TB-profiler 4.2.0 on a shared server to create a custom_db using this command "tb-profiler create_db -p tbdb_1 --custom --include_original_mutation" and it seem to have created all the necessary files (json,fasta etc). I moved all these new files to a new directory 'TEST'.

When i tried running ' tb-profiler profile --external_db TEST/tbdb_1 -1 R1.fastq.gz -2 R2.fastq.gz -p TE --txt', I get this error
set -u pipefail; rm ./9c8988dc-ad47-4c6e-80e2-b525b470ceb4_1U ./9c8988dc-ad47-4c6e-80e2-b525b470ceb4_2U
Traceback (most recent call last):
  File "/mnt/transient_data/conda/envs/tb-profiler/bin/tb-profiler", line 566, in <module>
    args.func(args)
  File "/mnt/transient_data/conda/envs/tb-profiler/bin/tb-profiler", line 150, in main_profile
    results.update(pp.run_profiler(args))
  File "/mnt/transient_data/conda/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 36, in run_profiler
    args.bam_file = get_bam_file(args)
  File "/mnt/transient_data/conda/envs/tb-profiler/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 106, in get_bam_file
    ref_file=args.conf["ref"], prefix=args.files_prefix,sample_name=args.prefix,
TypeError: 'NoneType' object is not subscriptable
Cleaning up after failed run
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/mnt/transient_data/conda/envs/tb-profiler/bin/tb-profiler", line 36, in cleanup
    O.write("* Database version: %s\n" % args.conf["version"]["commit"]) if "conf" in vars(args) else ""
TypeError: 'NoneType' object is not subscriptable

What might be the issue?? thanks

**Comment by jodyphelan** [comment]
It looks like loading the database did not work. I think this may be a bug with the version. Could you try add `--load` to your create_db command? and then just using `--db tbdb_1` in your profile command? 

Alternatively you could try upgrade to the latest version (v4.4.0)
